//! Two guards over the metric catalogue (decision 28).
//!
//! 1. **The reference page is generated**, from [`pub_telemetry::INSTRUMENTS`], and pinned
//!    byte-for-byte — the same contract `docs/ops/configuration.md` has. Regenerate with
//!    `UPDATE_METRICS_REFERENCE=1 cargo test -p pub-telemetry --test catalogue` (or `just gen`).
//! 2. **Every `metrics::*!` call site in the workspace is catalogued.** This is the guard that
//!    matters: before it existed, `architecture.md` documented 11 names against 21 emitted and
//!    nothing in the pipeline could tell. An instrument nobody can find is not observability,
//!    and a catalogue that drifts from the code is worse than none — it is confidently wrong.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use pub_telemetry::{INSTRUMENTS, InstrumentKind};

/// Repository root, from this crate's manifest (`server/crates/telemetry` → three levels up).
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn render_reference() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by server/crates/telemetry/tests/catalogue.rs from the INSTRUMENTS \
         catalogue — do not edit by hand.\n\
         Regenerate: just gen (or UPDATE_METRICS_REFERENCE=1 cargo test -p pub-telemetry --test catalogue) -->\n\n",
    );
    out.push_str("# Metrics reference\n\n");
    out.push_str(
        "Every instrument this build exports, straight from the catalogue the exporter \
         describes itself with. Nothing here is hand-maintained: a metric that is emitted but \
         missing from this page fails the build.\n\n",
    );
    out.push_str(
        "Exports are off by default. Set `telemetry.prometheus = true` and scrape \
         `telemetry.metrics_listen` (default `127.0.0.1:9090`), which is a **separate, \
         unauthenticated** listener — see [monitoring](monitoring.md) for the scrape config, \
         the alert rules, and why it is not a route on the application port.\n\n",
    );
    for instrument in INSTRUMENTS {
        let _ = writeln!(out, "## `{}`\n", instrument.name);
        let _ = writeln!(out, "*{}*\n", instrument.kind.as_str());
        if instrument.labels.is_empty() {
            out.push_str("No labels.\n\n");
        } else {
            let labels: Vec<String> = instrument.labels.iter().map(|label| format!("`{label}`")).collect();
            let _ = writeln!(out, "Labels: {}\n", labels.join(", "));
        }
        let _ = writeln!(out, "{}\n", instrument.help);
    }
    out
}

#[test]
fn the_committed_metrics_reference_matches_the_catalogue_exactly() {
    let rendered = render_reference();
    let path = workspace_root().join("docs/ops/metrics.md");
    if std::env::var_os("UPDATE_METRICS_REFERENCE").is_some() {
        std::fs::write(&path, rendered).expect("write docs/ops/metrics.md");
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "docs/ops/metrics.md could not be read ({err}). Generate it: \
             UPDATE_METRICS_REFERENCE=1 cargo test -p pub-telemetry --test catalogue   (or: just gen)"
        )
    });
    let (committed, rendered) = (committed.replace("\r\n", "\n"), rendered.replace("\r\n", "\n"));
    if committed != rendered {
        let diff = committed
            .lines()
            .zip(rendered.lines())
            .enumerate()
            .find(|(_, (a, b))| a != b)
            .map(|(i, (a, b))| format!("first difference at line {}:\n  committed: {a}\n  generated: {b}", i + 1))
            .unwrap_or_else(|| {
                format!(
                    "one file is a prefix of the other ({} vs {} lines)",
                    committed.lines().count(),
                    rendered.lines().count()
                )
            });
        panic!(
            "docs/ops/metrics.md does not match the INSTRUMENTS catalogue — the page is \
             generated output, never hand-edited ({diff}).\n\
             Regenerate: UPDATE_METRICS_REFERENCE=1 cargo test -p pub-telemetry --test catalogue   (or: just gen)"
        );
    }
}

/// Every metric name any crate emits, scanned out of the source.
///
/// A deliberately dumb scanner over `metrics::counter!("…"` / `gauge!` / `histogram!`: the
/// codebase writes every call site that way, and a scanner that understood more would be a
/// scanner that could be fooled. A call site spelled differently fails this test with a message
/// saying so, which is the correct outcome — the catalogue only works if every emission is
/// findable by the same rule.
fn emitted_names(root: &Path) -> BTreeSet<String> {
    const MACROS: &[&str] = &["counter!", "gauge!", "histogram!"];
    let mut names = BTreeSet::new();
    let mut stack = vec![root.join("server/crates")];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).unwrap_or_else(|err| panic!("read {}: {err}", dir.display())) {
            let path = entry.expect("dir entry").path();
            if path.is_dir() {
                if path.file_name().is_some_and(|name| name == "target") {
                    continue;
                }
                stack.push(path);
                continue;
            }
            if path.extension().is_none_or(|ext| ext != "rs") {
                continue;
            }
            let source = std::fs::read_to_string(&path).expect("read source");
            for (line_no, line) in source.lines().enumerate() {
                // Comment lines are prose — including this file's own explanation of what it
                // scans for, which would otherwise catalogue itself.
                if line.trim_start().starts_with("//") {
                    continue;
                }
                for macro_name in MACROS {
                    // `describe_*!` takes its name from the catalogue itself; skip it, or the
                    // scanner would just find the catalogue and prove nothing.
                    let mut rest = line;
                    while let Some(at) = rest.find(macro_name) {
                        let before = &rest[..at];
                        rest = &rest[at + macro_name.len()..];
                        if before.ends_with("describe_") {
                            continue;
                        }
                        let Some(open) = rest.strip_prefix('(') else { continue };
                        let Some(quoted) = open.strip_prefix('"') else {
                            panic!(
                                "{}:{}: a metric name must be a string literal so the catalogue can be checked \
                                 against it — found `{}`",
                                path.display(),
                                line_no + 1,
                                line.trim()
                            );
                        };
                        let end = quoted.find('"').expect("unterminated metric name literal");
                        names.insert(quoted[..end].to_owned());
                    }
                }
            }
        }
    }
    names
}

#[test]
fn every_emitted_instrument_is_catalogued_and_every_catalogued_one_is_emitted() {
    let emitted = emitted_names(&workspace_root());
    let catalogued: BTreeSet<String> = INSTRUMENTS.iter().map(|i| i.name.to_owned()).collect();

    let undocumented: Vec<&String> = emitted.difference(&catalogued).collect();
    assert!(
        undocumented.is_empty(),
        "these metrics are emitted but missing from the INSTRUMENTS catalogue, so they reach no \
         dashboard and no reference page: {undocumented:?}\n\
         Add them to server/crates/telemetry/src/catalogue.rs, then run just gen."
    );

    let unemitted: Vec<&String> = catalogued.difference(&emitted).collect();
    assert!(
        unemitted.is_empty(),
        "these metrics are catalogued but emitted nowhere, so the reference page promises data \
         that never arrives: {unemitted:?}"
    );
}

#[test]
fn the_catalogue_covers_both_the_http_metrics_and_the_mail_plane_signal() {
    // Two names the wave was built for; spelled out so a rename has to be deliberate.
    for required in ["http_requests_total", "http_request_duration_seconds", "mail_transport_unusable"] {
        assert!(INSTRUMENTS.iter().any(|i| i.name == required), "{required} must be catalogued");
    }
    assert!(
        INSTRUMENTS.iter().any(|i| i.kind == InstrumentKind::Histogram),
        "the upkeep task exists because of the histogram; a catalogue with none means it was removed"
    );
}
