/*
 * i18n codegen (decision 15, foxic-style). Run via `bun run i18n:gen`.
 *
 * Input:  packages/i18n/messages/<namespace>.yaml
 *         key: { en: string | plural-forms, desc: string, <locale>?: translation }
 * Output: packages/i18n/src/generated/<namespace>.ts
 *           — typed `as const` module with stable ids + bundled English
 *             (committed, Biome-excluded, never hand-edited)
 *         apps/site/public/locales/<locale>/<namespace>.json
 *           — per-locale dictionaries fetched lazily by the app; keys missing a
 *             translation are copied from English and listed in a "__todo__"
 *             marker entry (ignored by the runtime).
 */
import { readdir } from "node:fs/promises";
import { join } from "node:path";

const PKG_ROOT = join(import.meta.dir, "..");
const WEB_ROOT = join(PKG_ROOT, "..", "..");
const MESSAGES_DIR = join(PKG_ROOT, "messages");
const GENERATED_DIR = join(PKG_ROOT, "src", "generated");
const LOCALES_OUT_DIR = join(WEB_ROOT, "apps", "site", "public", "locales");

const LOCALES = ["en", "ru", "fr", "it", "de", "es", "pt", "ja", "ko", "zh-Hans"] as const;
const PLURAL_CATEGORIES = new Set(["zero", "one", "two", "few", "many", "other"]);
const KEY_PATTERN = /^[a-z][A-Za-z0-9]*$/;

type PluralForms = Record<string, string>;
type MessageValue = string | PluralForms;

function fail(message: string): never {
  console.error(`i18n-gen: ${message}`);
  process.exit(1);
}

function isPluralForms(value: unknown): value is PluralForms {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const entries = Object.entries(value);
  return (
    entries.length > 0 &&
    entries.every(([k, v]) => PLURAL_CATEGORIES.has(k) && typeof v === "string")
  );
}

function parseValue(raw: unknown, where: string): MessageValue {
  if (typeof raw === "string") return raw;
  if (isPluralForms(raw)) {
    if (raw.other === undefined) fail(`${where}: plural forms must include "other"`);
    return raw;
  }
  return fail(`${where}: expected a string or a plural-form map (zero/one/two/few/many/other)`);
}

const files = (await readdir(MESSAGES_DIR)).filter((f) => f.endsWith(".yaml")).sort();
if (files.length === 0) fail(`no .yaml files found in ${MESSAGES_DIR}`);

for (const file of files) {
  const namespace = file.replace(/\.yaml$/, "");
  const parsed: unknown = Bun.YAML.parse(await Bun.file(join(MESSAGES_DIR, file)).text());
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    fail(`${file}: root must be a mapping of keys`);
  }

  // key -> { desc, values per locale } — insertion order is preserved everywhere.
  const messages = new Map<string, { desc: string; values: Map<string, MessageValue> }>();

  for (const [key, rawEntry] of Object.entries(parsed)) {
    const where = `${file}:${key}`;
    if (!KEY_PATTERN.test(key)) fail(`${where}: key must be camelCase ([a-z][A-Za-z0-9]*)`);
    if (typeof rawEntry !== "object" || rawEntry === null) fail(`${where}: must be a mapping`);
    const entry = rawEntry as Record<string, unknown>;

    const desc = entry.desc;
    if (typeof desc !== "string" || desc.trim() === "") {
      fail(`${where}: mandatory "desc" is missing or empty`);
    }
    if (entry.en === undefined) fail(`${where}: mandatory "en" is missing`);
    const en = parseValue(entry.en, where);

    const values = new Map<string, MessageValue>([["en", en]]);
    for (const [field, rawValue] of Object.entries(entry)) {
      if (field === "en" || field === "desc") continue;
      if (!(LOCALES as readonly string[]).includes(field)) {
        fail(`${where}: "${field}" is not a supported locale (${LOCALES.join(" ")})`);
      }
      const value = parseValue(rawValue, `${where}.${field}`);
      if (typeof value !== typeof en) {
        fail(`${where}.${field}: shape must match "en" (both plain or both plural)`);
      }
      values.set(field, value);
    }
    messages.set(key, { desc, values });
  }

  // 1) Typed module with bundled English (the runtime fallback).
  const lines: string[] = [
    "// AUTO-GENERATED by packages/i18n/scripts/i18n-gen.ts — DO NOT EDIT.",
    `// Source: packages/i18n/messages/${file}. Regenerate: \`bun run i18n:gen\`.`,
    "",
    `export const ${namespace} = {`,
  ];
  for (const [key, { desc, values }] of messages) {
    const en = values.get("en");
    lines.push(`  /** ${desc} */`);
    lines.push(`  ${key}: { id: "${namespace}.${key}", en: ${JSON.stringify(en)} },`);
  }
  lines.push("} as const;", "");
  await Bun.write(join(GENERATED_DIR, `${namespace}.ts`), lines.join("\n"));

  // 2) Per-locale JSON dictionaries.
  for (const locale of LOCALES) {
    const dict: Record<string, MessageValue> = {};
    const todo: string[] = [];
    for (const [key, { values }] of messages) {
      const value = values.get(locale);
      if (value === undefined && locale !== "en") todo.push(key);
      dict[`${namespace}.${key}`] = value ?? (values.get("en") as MessageValue);
    }
    const output: Record<string, MessageValue> =
      todo.length > 0
        ? { __todo__: `TODO: translate from English: ${todo.join(", ")}`, ...dict }
        : dict;
    const path = join(LOCALES_OUT_DIR, locale, `${namespace}.json`);
    await Bun.write(path, `${JSON.stringify(output, null, 2)}\n`);
  }

  console.log(`i18n-gen: ${namespace} — ${messages.size} keys, ${LOCALES.length} locales`);
}
